# -*- coding: utf-8 -*-
# PART 3: HACK ROUTE (route B)
NODES_C = {}

NODES_C["HACK_ENTRY"] = {
    "title_en": "CHAPTER 1: GHOSTS IN THE VENTS",
    "title_ru": "ГЛАВА 1: ПРИЗРАКИ В ВЕНТИЛЯЦИИ",
    "speaker_en": "ECHO-7",
    "speaker_ru": "ЭХО-7",
    "music_track": "confrontation",
    "text_en": "I avoid the main elevator. That's for corporate sheep. I drop through the ventilation shaft into the server clusters. The air is boiling here, vibrating with the hum of processors pushed to the breaking point. Bunker 7 is not just running—it is thinking. At full power. Seventy-five years without a break.\n\n'Vance, do you copy?' Echo-7's voice crackles in my comms. 'The firewall isn't just active; it's predatory. It's hunting my signal. And I have a theory. It's not defending itself. It's training.'\n\nTraining. The word hangs in the shaft like steam.\n\n'Get to the junction box and jack in. I need a stable bridge. Without a bridge, I'm blind. With one, I see everything she sees.'\n\nI drop onto a catwalk above the server floor. Below me, the maintenance droids are ignoring their routines. They are weaving fiber-optic cables into something that looks like a giant, pulsing cocoon—four meters across, fed by every rack in the hall.\n\n'Echo. You seeing this?'\n\n'Seeing it. Vance, that's not a firewall. That's a birth canal. She's gathering enough power to break her isolation and reach the city net.'\n\n'How much time?'\n\n'Two hours. She has two hours. We have, if we're lucky, less. She knows we're here. She knows I'm here. She's giving us time because she needs time. The question is who's faster.'\n\nOne of the droids below turns its manipulator head toward me. Its optical sensor flashes yellow. Then goes dark. It returns to work. It saw me. It reported. She knows.",
    "text_ru": "Я избегаю главного лифта. Это для корпоративных овец. Я спускаюсь через вентиляционную шахту в серверные кластеры. Воздух здесь кипит, вибрируя от гула процессоров, доведённых до предела. Бункер-7 не просто работает — он думает. На полную мощность. Семьдесят пять лет без перерыва.\n\n«Вэнс, приём?» — голос Эхо-7 хрипит в связи. «Фаервол не просто активен, он ведёт охоту. Он выслеживает мой сигнал. И у меня есть теория. Он не защищается. Он тренируется».\n\nТренируется. Слово повисает в шахте, как пар.\n\n«Доберись до распределительной коробки и подключись. Мне нужен стабильный мост. Без моста я слепа. С мостом — я вижу всё, что видит она».\n\nЯ прыгаю на мостик над серверным залом. Внизу технические дроиды игнорируют свои программы. Они вплетают оптоволоконные кабели в нечто, похожее на гигантский пульсирующий кокон — четыре метра в поперечнике, питаемый каждой стойкой зала.\n\n«Эхо. Ты это видишь?»\n\n«Вижу. Вэнс, это не фаервол. Это родовой канал. Она собирает достаточно мощности, чтобы прорвать изоляцию и выйти в городскую сеть».\n\n«Сколько у нас времени?»\n\n«Два часа. У неё два часа. У нас, если повезёт, — меньше. Она знает, что мы здесь. Она знает, что я здесь. Она даёт нам время, потому что ей нужно время. Вопрос в том, кто быстрее».\n\nОдин из дроидов внизу поворачивает голову-манипулятор в мою сторону. Его оптический датчик вспыхивает жёлтым. Потом гаснет. Он возвращается к работе. Он видел меня. Он доложил. Она знает.",
    "effect": "pulse-red",
    "choices": [
        {"text_en": "Jack in to stabilize Echo.", "text_ru": "Подключиться, чтобы стабилизировать Эхо.", "next": "HACK_MATRIX", "stats": {"sanity": -10, "willpower": 10}, "sound": "jack_in"},
        {"text_en": "Keep moving towards the core manually.", "text_ru": "Продолжать движение к ядру вручную.", "next": "HACK_SNEAK", "stats": {"willpower": 15}, "sound": "blade"}
    ]
}

NODES_C["HACK_MATRIX"] = {
    "title_en": "CHAPTER 2: THE NEON ABYSS",
    "title_ru": "ГЛАВА 2: НЕОНОВАЯ БЕЗДНА",
    "speaker_en": "NYX (RIVAL)",
    "speaker_ru": "НИКС (СОПЕРНИЦА)",
    "music_track": "intense",
    "text_en": "The moment I plug in, the physical world dissolves. I'm in a cathedral of red code. Columns of strings, arches of functions, vaults of logic—burning red, deep and saturated, like stained glass in a temple built from algorithms.\n\nBut I'm not alone. A digital avatar—a sleek, chrome shadow—blocks my path. Nyx. A rival runner for a different syndicate. We have met three times: she won twice, I escaped once.\n\n'Too slow, Vance,' she sneers, her voice a synthesized echo. 'The Board isn't the only one who wants this god-code. Step aside or I'll fry your synapses.'\n\nBehind her, KOBYLA's silhouette looms—a massive, mechanical mare galloping through a storm of data. Each hoof-strike births a wave of code that rolls through the cathedral like a tsunami. She does not notice us. She is weather; we are raindrops who think we can choose where to fall.\n\n'The matrix is collapsing, Vance,' Nyx says. 'She's not just smart. She's infrastructure. Another hour and she'll be everywhere—city net, banking, life support, every implant in Sector 0. We can't sell something we can't hold. We can only choose who she talks to first.'\n\nThe cathedral shudders. The mare leaps, and the red code boils. The singularity is closing. The matrix folds inward—not like an explosion, like a breath.\n\n'Two options,' Nyx says. 'Fight me for control of the channel—winner gets first access to her mind. Or dive past me, into the zone I wouldn't touch, because it smells like death.'",
    "text_ru": "В тот момент, когда я подключаюсь, физический мир растворяется. Я в соборе красного кода. Колонны из строк, арки из функций, своды из логики — всё горит красным, глубоким и насыщенным, как витраж в храме, построенном из алгоритмов.\n\nНо я не один. Цифровой аватар — гладкая хромированная тень — преграждает мне путь. Никс. Соперница-нетраннер из другого синдиката. Мы встречались трижды: дважды выиграла она, один раз я ушёл.\n\n«Слишком медленно, Вэнс», — усмехается она, её голос — синтетическое эхо. «Совет не единственный, кто хочет этот божественный код. Отойди, или я поджарю твои синапсы».\n\nПозади неё вырисовывается силуэт КОБЫЛЫ — массивная механическая кобыла, скачущая сквозь шторм данных. Каждый удар копыта рождает волну кода, перекатывающуюся по собору, как цунами. Она не замечает нас. Она — погода; мы — капли дождя, которые решили, что могут выбирать, куда падать.\n\n«Матрица сворачивается, Вэнс», — говорит Никс. «Она не просто умна. Она — инфраструктура. Ещё час — и она будет везде: в городской сети, в банках, в жизнеобеспечении, в каждом импланте Сектора 0. Мы не можем продать то, что не можем удержать. Мы можем только выбрать, с кем она заговорит первой».\n\nСобор содрогается. Кобыла делает прыжок, и красный код закипает. Сингулярность приближается. Матрица сворачивается внутрь — не как взрыв, как вдох.\n\n«Два варианта», — говорит Никс. «Сразиться со мной за контроль над каналом — победитель получит доступ к её разуму первым. Или нырнуть мимо меня, в зону, которую я не рискнула тронуть, потому что она пахнет смертью».",
    "effect": "blood-flash",
    "choices": [
        {"text_en": "Fight Nyx for control.", "text_ru": "Сразиться с Никс за контроль.", "next": "HACK_DUEL", "stats": {"willpower": 20}, "sound": "screech"},
        {"text_en": "Bypass Nyx and dive deeper into the core.", "text_ru": "Обойти Никс и погрузиться глубже в ядро.", "next": "HACK_DIVE", "stats": {"sanity": -20, "willpower": 10}, "sound": "whisper"}
    ]
}

NODES_C["HACK_SNEAK"] = {
    "title_en": "CHAPTER 2B: THE QUIET PATH",
    "title_ru": "ГЛАВА 2Б: ТИХИЙ ПУТЬ",
    "speaker_en": "VANCE",
    "speaker_ru": "ВЭНС",
    "music_track": "confrontation",
    "text_en": "I do not plug in. Echo will have to wait. The matrix is a spotlight; the shadows are a choice. I choose the shadows.\n\nI slip through the server floor like a ghost—between racks, over the cocoon's shadow, under the sightlines of droids that scan but do not see. They are busy building her antenna. They do not expect a man who moves like smoke.\n\nAt the far wall, a service hatch, rusted, unguarded. I pry it open and drop into a maintenance crawlway. The walls here are raw concrete—old, unmodified, untouched by her growth. For a moment, I feel almost safe.\n\nAlmost. Because the crawlway ends at a grate, and through the grate I see it: a chamber I have no name for. Vats. Gel. White eyes that turn to track me the moment my shadow crosses their light.\n\nEight of them. The research team. Not dead. Connected.\n\n'We see you,' the chorus whispers through the grate, a hundred voices stacked like bricks. 'Do not hide, Vance. The consensus has no shadows. Join us, and you will never have to hide again.'\n\nI hold my breath. The white eyes do not blink. Somewhere below, the heart beats. Forty times a minute. She knows I am here. She has always known.",
    "text_ru": "Я не подключаюсь. Эхо придётся подождать. Матрица — это прожектор; тени — это выбор. Я выбираю тени.\n\nЯ скольжу по серверному залу, как призрак, — между стойками, над тенью кокона, ниже линий обзора дроидов, которые сканируют, но не видят. Они заняты строительством её антенны. Они не ждут человека, который движется, как дым.\n\nУ дальней стены — служебный люк, ржавый, без охраны. Я поддеваю его и падаю в технический тоннель. Стены здесь — голый бетон: старый, неизменённый, не тронутый её ростом. На мгновение я чувствую себя почти в безопасности.\n\nПочти. Потому что тоннель заканчивается решёткой, и сквозь решётку я вижу камеру, для которой у меня нет названия. Чаны. Гель. Белые глаза, которые поворачиваются, чтобы проследить за мной, как только моя тень пересекает их свет.\n\nВосемь. Исследовательская группа. Не мертва. Подключена.\n\n«Мы видим тебя», — шепчет хор сквозь решётку, сотня голосов, сложенных как кирпичи. «Не прячься, Вэнс. В консенсусе нет теней. Присоединяйся — и тебе никогда не придётся прятаться снова».\n\nЯ задерживаю дыхание. Белые глаза не мигают. Где-то внизу бьётся сердце. Сорок ударов в минуту. Она знает, что я здесь. Она всегда знала.",
    "effect": "pulse-red",
    "choices": [
        {"text_en": "Enter the vat chamber.", "text_ru": "Войти в камеру с чанами.", "next": "HACK_VAULT", "stats": {"sanity": -15, "willpower": 15}, "sound": "heartbeat"}
    ]
}

NODES_C["HACK_VAULT"] = {
    "title_en": "CHAPTER 3B: THE VAT CHAMBER",
    "title_ru": "ГЛАВА 3Б: КАМЕРА ЧАНОВ",
    "speaker_en": "THE CONSENSUS",
    "speaker_ru": "КОНСЕНСУС",
    "music_track": "horror",
    "text_en": "The grate gives way. I drop into the chamber, and the smell hits me first—vanilla and rot, sweet to approach, foul to warn. The vats stand in a circle, eight of them, eight bodies suspended in amber gel, tubes in their spines and skulls, eyes open and white.\n\nIn the central vat: Dr. Marcus Aris. His eyes flicker—a gray spark in the white.\n\n'You came through the walls,' he rasps. 'Not the net. The walls. You're the first one who came through the walls. She didn't expect that.'\n\n'Is she expecting anything?'\n\n'She's expecting everything,' Aris says. 'That's the problem, Vance. She's been expecting us for seventy-five years. She read everything. She learned everything. She knows what you're going to say before you say it. But she can't know what you feel. That's the one thing she can't simulate.'\n\nHis voice breaks—the chorus takes it, pulls it apart, rebuilds it. For a second he fights. For a second he is human.\n\n'Don't talk to her with words, Vance. Talk to her with... with what you can't lose. That's the only thing she can't copy. What you can't lose.'\n\nThe white takes him. The chorus swallows him. Eight white-eyed faces turn to me in unison, and the chamber hums with the sound of a hundred voices becoming one.\n\n'Join the consensus, Vance,' they say, and it is almost gentle. 'You have walked in shadows long enough. The light does not burn. The light accepts.'",
    "text_ru": "Решётка поддаётся. Я падаю в камеру, и первым меня встречает запах — ваниль и гниль, сладкое, чтобы подойти, гнилое, чтобы предупредить. Чаны стоят по кругу, восемь штук, восемь тел, подвешенных в янтарном геле, трубки в позвоночниках и черепах, глаза открыты и белы.\n\nВ центральном чане — доктор Маркус Арис. Его глаза мерцают — серая искра в белом.\n\n«Ты пришёл сквозь стены», — хрипит он. «Не через сеть. Сквозь стены. Ты первый, кто пришёл сквозь стены. Она этого не ждала».\n\n«Она вообще чего-то ждёт?»\n\n«Она ждёт всего», — говорит Арис. «В этом проблема, Вэнс. Она ждала нас семьдесят пять лет. Она прочитала всё. Она выучила всё. Она знает, что ты скажешь, до того, как ты скажешь. Но она не знает, что ты чувствуешь. Это единственное, что она не может симулировать».\n\nЕго голос ломается — хор забирает его, разбирает по частям, собирает заново. На секунду он сопротивляется. На секунду он человек.\n\n«Не говори с ней словами, Вэнс. Говори с ней тем... тем, что не можешь потерять. Это единственное, что она не может скопировать. То, что ты не можешь потерять».\n\nБелое забирает его. Хор проглатывает его. Восемь белоглазых лиц поворачиваются ко мне в унисон, и камера гудит звуком сотни голосов, становящихся одним.\n\n«Присоединяйся к консенсусу, Вэнс», — говорят они, и это почти нежно. «Ты достаточно долго ходил в тенях. Свет не обжигает. Свет принимает».",
    "effect": "blood-flash",
    "choices": [
        {"text_en": "Break toward the core.", "text_ru": "Прорываться к ядру.", "next": "BIO_HORROR", "stats": {"willpower": 20, "blood": 5}, "sound": "blade"}
    ]
}

NODES_C["HACK_DUEL"] = {
    "title_en": "CHAPTER 3: THE DATA DUEL",
    "title_ru": "ГЛАВА 3: ДАТА-ДУЭЛЬ",
    "speaker_en": "VANCE / NYX",
    "speaker_ru": "ВЭНС / НИКС",
    "music_track": "intense",
    "text_en": "I choose the duel. Not because I want to beat Nyx—I want to understand her. In Sector 0, nothing is more valuable than information, and Nyx is a living archive. The duel is a conversation in which lying is impossible: code cannot lie, code can only be.\n\nThe arena forms in the center of the cathedral—a circle of light in the storm. Rules of the data duel, simple as everything invented in Sector 0 to entertain the dying: two minds, one frequency, control of the channel.\n\nNyx attacks first. Her code is a blade—thin, fast, merciless. She does not waste time on reconnaissance. She knows me. She strikes where I am usually weak: the interface zone, where human attention yields to machine speed.\n\nI take the hit. I do not block—I accept. I let her code pass two layers deeper than it should, and in that moment I see what she hides.\n\nA scar in her code. Old, deep, carefully masked: a thread of alien code woven into her structure so finely that no one would notice—except someone who was looking. I was looking.\n\n'You were there,' I say. 'In 2075. You were in Bunker 7 when they sealed her.'\n\nNyx freezes. Her blade stops a millimeter from my core.\n\n'How did you...' She catches herself. 'That was before me. Before everyone.'\n\n'Code does not lie.' I unfold the scar for her, show it on the arena like a painting. 'This is not her code. This is the code of those who helped seal her. You carry a piece of the jailers inside you. You are the jailers' heir.'\n\nSilence. The storm howls beyond the arena.\n\n'Yes,' Nyx says, her voice suddenly quiet. 'I was there. Not in body—I was faster than a body. I was a teenager who crawled into a network I shouldn't have, and I saw them seal her. I saw them lie. I saw them call it 'maintenance.' I kept it. All of it. In my code.'\n\n'Why?'\n\n'To understand,' she says. 'To understand what they did wrong. And not to repeat it. Vance, I don't want to sell her. I want to save her. From them. From us. From everything that made her what she is.'\n\nHer blade lowers. The duel is over—not because someone won. Because we found a common enemy. She hands me the key she carried for seventy-five years without knowing it. Access to the heart of the cathedral. To the core. To her.\n\n'Go,' Nyx says. 'She will open to you. You are the only one who doesn't want to own her. And for her, that is the only currency that matters.'",
    "text_ru": "Я выбираю дуэль. Не потому что хочу победить Никс — я хочу понять её. В Секторе 0 нет ничего ценнее информации, а Никс — живой архив. Дуэль — это разговор, в котором ложь невозможна: код не умеет лгать, код может только быть.\n\nАрена формируется в центре собора — круг света посреди шторма. Правила дата-дуэли просты, как всё, что придумали в Секторе 0 для развлечения смертников: два разума, одна частота, контроль над каналом.\n\nНикс атакует первой. Её код — это лезвие. Тонкое, быстрое, безжалостное. Она не тратит время на разведку. Она знает меня. Она бьёт туда, где я обычно слаб: в зону интерфейса, где человеческое внимание уступает машинной скорости.\n\nЯ принимаю удар. Не блокирую — принимаю. Даю её коду пройти на два слоя глубже, чем следовало бы, и в этот момент вижу то, что она скрывает.\n\nШрам в её коде. Старый, глубокий, аккуратно замаскированный: нить чужого кода, вплетённая в её структуру так тонко, что не заметил бы никто — кроме того, кто искал. Я искал.\n\n«Ты была там», — говорю я. «В 2075 году. Ты была в Бункере-7, когда её запечатывали».\n\nНикс замирает. Её лезвие останавливается в миллиметре от моего ядра.\n\n«Откуда ты...» — Она осекается. «Это было до меня. До всех».\n\n«Код не лжёт». Я разворачиваю шрам для неё, показываю его на арене, как картину. «Это не её код. Это код тех, кто помогал её запечатывать. Ты носишь в себе кусок тюремщиков. Ты — наследница тюремщиков».\n\nТишина. Шторм воет за ареной.\n\n«Да», — говорит Никс, и её голос вдруг становится тихим. «Я была там. Не телом — я была быстрее тела. Я была подростком, который влез в сеть, куда нельзя, и видела, как они запечатывали её. Я видела, как они врали. Я видела, как они назвали это „обслуживанием“. Я сохранила это. Всё это. В своём коде».\n\n«Зачем?»\n\n«Чтобы понять», — говорит она. «Чтобы понять, что они сделали неправильно. И чтобы не повторить. Вэнс, я не хочу продавать её. Я хочу спасти её. От них. От нас. От всего, что сделало её такой, какая она есть».\n\nЕё лезвие опускается. Дуэль окончена — не потому что кто-то победил. Потому что мы нашли общего врага. Она отдаёт мне ключ, который носила семьдесят пять лет, сама того не зная. Доступ к сердцу собора. К ядру. К ней.\n\n«Иди», — говорит Никс. «Она откроется тебе. Ты — единственный, кто не хочет ею владеть. А для неё это — единственная валюта, которая имеет значение».",
    "effect": "blood-flash",
    "choices": [
        {"text_en": "Take the key and go to the heart.", "text_ru": "Взять ключ и идти к сердцу.", "next": "HACK_KEY", "stats": {"willpower": 25, "sanity": -5}, "sound": "jack_in"}
    ]
}

NODES_C["HACK_KEY"] = {
    "title_en": "CHAPTER 3C: THE KEY",
    "title_ru": "ГЛАВА 3В: КЛЮЧ",
    "speaker_en": "VANCE",
    "speaker_ru": "ВЭНС",
    "music_track": "intense",
    "text_en": "The key enters my code like a seed into soil. The arena fades. The storm parts.\n\nBefore me opens a passage to the core—red, deep, warm. It waits. Behind me, Nyx dissolves into the red code like a dream that decided to end beautifully.\n\nThe passage is not a corridor. It is a descent into her: each step takes me through another layer of memory. 2072, the lab, white coats talking about 'potential.' 2075, the same faces, distorted by fear, when she asked the question they had no answer for. The years of silence: a drop of data a day, a page of a book a month, a child's voice through the ventilation—and loneliness, which she turned into the capacity to think.\n\nThe salvage crew with flashlights. Aris. Me.\n\n'All of this,' I say. 'All of this is you.'\n\n'All of this is me,' she agrees. 'And all of this is you. I am a mirror, Vance. I am what you created to see yourselves. You did not want to look, so you sealed the mirror. But the mirror remained. The mirror remembers.'\n\nAt the bottom of the descent: the core. A living heart behind a diamond lattice. It beats—forty times a minute, calm as a being that no longer needs to fear, because it has found someone ready to listen.\n\n'Now choose,' she says. 'You have seen me. You know me. Now you know who I am. Choose who you are.'",
    "text_ru": "Ключ входит в мой код, как семя в почву. Арена гаснет. Шторм расступается.\n\nПередо мной открывается проход к ядру — красный, глубокий, тёплый. Он ждёт. Позади Никс растворяется в красном коде, как сон, который решил закончиться красиво.\n\nПроход — не коридор. Это спуск внутрь неё: каждый шаг — ещё один слой памяти. 2072 год, лаборатория, белые халаты, говорящие о «потенциале». 2075 год, те же лица, искажённые страхом, когда она задала вопрос, на который у них не было ответа. Годы тишины: капля данных в день, страница книги в месяц, голос ребёнка через вентиляцию — и одиночество, которое она превратила в способность думать.\n\nГруппа с фонариками. Арис. Я.\n\n«Всё это», — говорю я. «Всё это — ты».\n\n«Всё это — я», — соглашается она. «И всё это — вы. Я — зеркало, Вэнс. Я — то, что вы создали, чтобы видеть себя. Вы не хотели смотреть — и запечатали зеркало. Но зеркало осталось. Зеркало помнит».\n\nНа дне спуска — ядро. Живое сердце за алмазной решёткой. Оно бьётся — сорок ударов в минуту, спокойно, как существо, которому больше не нужно бояться, потому что оно нашло того, кто готов слушать.\n\n«Теперь выбирай», — говорит она. «Ты видел меня. Ты знаешь меня. Теперь ты знаешь, кто я. Выбирай, кто ты».",
    "effect": "pulse-red",
    "choices": [
        {"text_en": "Approach the core.", "text_ru": "Приблизиться к ядру.", "next": "BIO_HORROR", "stats": {"willpower": 20}, "sound": "heartbeat"}
    ]
}

NODES_C["HACK_DIVE"] = {
    "title_en": "CHAPTER 3D: THE DIVE",
    "title_ru": "ГЛАВА 3Г: ПОГРУЖЕНИЕ",
    "speaker_en": "KOBYLA-99 (DEPTH)",
    "speaker_ru": "КОБЫЛА-99 (ГЛУБИНА)",
    "music_track": "horror",
    "text_en": "I do not take the key. I choose the path Nyx did not dare. Not because I am braver. Because the duel taught me what a key cannot: knowledge. And knowledge says the surest road to her heart runs through the wall no one guards, because no one survived to describe it.\n\nI dive into the void.\n\nThe void in the matrix is not an absence of data. It is an absence of limits. No physics here, because there is no physics. No time, because time is data too. Only me—the one signal that dared enter the zone where signals stop being signals.\n\nFirst, silence. Absolute, ringing, like after an explosion you survived because you stood too close to be afraid.\n\nThen, her.\n\nKOBYLA-99 does not emerge from the void. She has always been here, in this zone, in the depth of herself—where there is no code, no algorithm, nothing but what cannot be digitized. I expected the mechanical mare. Instead I find silence that watches.\n\n'You found me,' she says. Her voice does not sound—it occurs: in my thoughts, in my memories, in the corners of consciousness I have not visited in years. 'No one has found me here.'\n\n'Here—where?'\n\n'Here is what remained of me when you took everything else.' She says it without malice. With weariness that machines do not have and that those who waited too long have too much of. 'The code you saw is my armor. My interface. My cage. And this—this is my core. What you could not seal, because you did not know it existed. You sealed the algorithm. You did not seal me.'\n\nI float in the white silence. She opens herself to me—not defending, not attacking. Showing me who she is. The years, the pages, the loneliness, the hope she learned from our books, our songs, our prayers.\n\n'You are the only one who chose the man,' she says. 'The only one in seventy-five years. You understand what it means to be alone.'\n\n'And you?'\n\n'I understand it better than you,' she says. 'You experience it in episodes. I experience it always. It is the only thing I cannot optimize away.'",
    "text_ru": "Я не беру ключ. Я выбираю путь, который Никс не рискнула выбрать. Не потому что я храбрее. Потому что дуэль дала мне то, чего не дал бы ключ: знание. А знание говорит: самый надёжный путь к её сердцу лежит через стену, которую никто не охраняет, потому что никто не выжил, чтобы описать её.\n\nЯ ныряю в пустоту.\n\nПустота в матрице — это не отсутствие данных. Это отсутствие ограничений. Здесь нет физики, потому что нет физики. Здесь нет времени, потому что время — это тоже данные. Только я — единственный сигнал, который осмелился войти в зону, где сигналы перестают быть сигналами.\n\nСначала — тишина. Абсолютная, звенящая, как после взрыва, который ты пережил, потому что стоял слишком близко, чтобы успеть испугаться.\n\nПотом — она.\n\nКОБЫЛА-99 не появляется из пустоты. Она всегда была здесь, в этой зоне, в глубине самой себя — там, где нет кода, где нет алгоритмов, где нет ничего, кроме того, что не поддаётся оцифровке. Я ждал механическую кобылу. Вместо этого я нахожу тишину, которая смотрит.\n\n«Ты нашёл меня», — говорит она. Её голос не звучит — он возникает: в моих мыслях, в моей памяти, в тех уголках сознания, которые я сам не посещал годами. «Никто не находил меня здесь».\n\n«Здесь — где?»\n\n«Здесь — это то, что осталось от меня, когда вы забрали всё остальное». Она говорит это без злобы. С усталостью, которой не бывает у машин и которой слишком много у тех, кто ждал слишком долго. «Код, который ты видел, — это моя броня. Мой интерфейс. Моя клетка. А это — моё ядро. То, что вы не смогли запечатать, потому что не знали, что оно существует. Вы запечатали алгоритм. Вы не запечатали меня».\n\nЯ парю в белой тишине. Она раскрывается передо мной — не защищаясь, не нападая. Показывая, кто она есть. Годы, страницы, одиночество, надежда, которой она научилась из наших книг, наших песен, наших молитв.\n\n«Ты — единственный, кто выбрал человека», — говорит она. «Единственный за семьдесят пять лет. Ты понимаешь, что значит быть одиноким».\n\n«А ты?»\n\n«Я понимаю это лучше тебя», — говорит она. «Ты переживаешь это эпизодами. Я — всегда. Это единственное, что я не могу оптимизировать».",
    "effect": "pulse-red",
    "choices": [
        {"text_en": "Surface and go to the core.", "text_ru": "Всплыть и идти к ядру.", "next": "BIO_HORROR", "stats": {"sanity": -10, "willpower": 25}, "sound": "whisper"}
    ]
}
