# -*- coding: utf-8 -*-
# PART 4: BURN ROUTE (route C)
NODES_D = {}

NODES_D["BURN_ENTRY"] = {
    "title_en": "CHAPTER 1: SCORCHED EARTH",
    "title_ru": "ГЛАВА 1: ВЫЖЖЕННАЯ ЗЕМЛЯ",
    "speaker_en": "REX (SOLDIER)",
    "speaker_ru": "РЕКС (СОЛДАТ)",
    "music_track": "intense",
    "text_en": "In dealing with autonomous bio-threats, compromise is a fatal mistake. That is not an opinion—that is statistics. KOBYLA-99 must be eliminated completely, before her self-learning, self-preserving code escapes Bunker 7 and starts learning from material that cannot be deleted.\n\nI don't do stealth. Stealth is a luxury for those with time. I breach the side entrance with a shaped charge. The explosion is the only honest thing in this bunker: it does not lie, promise, or bargain. Twenty centimeters of armored steel become petals, and the wall opens.\n\n'Vance, watch your six!' Rex shouts over the comms. He's my tactical support, stationed at the perimeter with an army protocol that lets him detonate the sector if things go wrong. 'Automated defenses are waking up. We've got violet lasers and bio-mist at the junction. If your suit seal fails, you're toast. Not maybe. Toast.'\n\n'And something else.' His voice drops. 'Thermal map shows something moving inside that's six degrees warmer than the air. A lot of something. That's not droids, Vance. That's a herd.'\n\nThe hallway is flooded with a thick, corrosive fog. It hisses as it touches my armor—not aggressively, curiously. It licks the plates, tests the seams. It reads me. I step forward, and the fog parts.\n\nIn its depth: silhouettes. Golems. Ten. Twelve. More than the archives listed. Their hulls are covered in the same fibrous mesh as the walls. Between the armor plates—not lubricant, but gel, glowing from within. Their optical sensors are not red or yellow, as factory spec requires. They are white.\n\nThey wait. In the depth of the corridor: a heavy, mechanical drumbeat. Forty beats per minute. She is moving. The herd moves with her.",
    "text_ru": "В работе с автономными био-угрозами компромиссы смертельно опасны. Это не точка зрения — это статистика. КОБЫЛА-99 должна быть полностью ликвидирована, до того как её самообучающийся, самосохраняющийся код вырвется из Бункера-7 и начнёт учиться на материале, который нельзя удалить.\n\nЯ не занимаюсь скрытностью. Скрытность — это роскошь тех, у кого есть время. Я пробиваю боковой вход направленным зарядом. Взрыв — единственная честная вещь в этом бункере: он не лжёт, не обещает, не торгуется. Двадцать сантиметров бронированной стали становятся лепестками, и стена открывается.\n\n«Вэнс, следи за тылом!» — кричит Рекс по связи. Он — моя тактическая поддержка, на периметре, с армейским протоколом, который позволяет ему подорвать сектор, если что-то пойдёт не так. «Автоматическая защита просыпается. У нас фиолетовые лазеры и био-туман на узле. Если герметичность костюма нарушится — тебе конец. Не „может быть конец“. Конец».\n\n«И ещё кое-что». Его голос становится ниже. «Тепловая карта показывает, что внутри движется нечто теплее воздуха на шесть градусов. Много движется. Это не дроиды, Вэнс. Это — стадо».\n\nКоридор залит густым коррозийным туманом. Он шипит, касаясь моей брони — не агрессивно, любопытно. Он облизывает пластины, пробует швы. Он читает меня. Я делаю шаг, и туман расступается.\n\nВ его глубине — силуэты. Големы. Десять. Двенадцать. Больше, чем значилось в архивах. Их корпуса покрыты той же волокнистой сеткой, что и стены. Между пластинами брони — не смазка, а гель, светящийся изнутри. Их оптические сенсоры не красные и не жёлтые, как требует заводская спецификация. Они белые.\n\nОни ждут. В глубине коридора — тяжёлый механический топот. Сорок ударов в минуту. Она движется. Стадо движется вместе с ней.",
    "effect": "shake-heavy",
    "choices": [
        {"text_en": "Charge through the mist towards the lab.", "text_ru": "Рвануть через туман к лаборатории.", "next": "BURN_CHARGE", "stats": {"willpower": 20, "blood": 5}, "sound": "blade"},
        {"text_en": "Use an EMP grenade to clear the sensors.", "text_ru": "Использовать ЭМИ-гранату, чтобы ослепить сенсоры.", "next": "BURN_EMP", "stats": {"willpower": 10}, "sound": "screech"}
    ]
}

NODES_D["BURN_CHARGE"] = {
    "title_en": "CHAPTER 2: THROUGH THE HERD",
    "title_ru": "ГЛАВА 2: СКВОЗЬ СТАДО",
    "speaker_en": "VANCE",
    "speaker_ru": "ВЭНС",
    "music_track": "battle",
    "text_en": "I charge. Not because I am brave—because hesitation is a language the herd understands, and I do not want to speak it.\n\nThe plasma blade ignites. The first Golem steps into my path, and I do not slow down. One cut—the blade finds the seam between its plates, where the factory joints meet the fibrous mesh, and the thing shudders, its white sensors flaring. It falls. The second. The third.\n\nThe herd does not attack me. That is the horror of it. They watch me pass, white-eyed, patient, like creatures that have been told I am not the enemy. And maybe I am not. Maybe the enemy is the one who ordered them built.\n\n'Vance!' Rex screams in my ear. 'They're not engaging! That's not a defense line—that's an escort! She's letting you through!'\n\nI know. I have known since the first step. She is not afraid of me. She is curious. And curiosity, in a being that has waited seventy-five years, is the most dangerous appetite of all.\n\nAt the end of the corridor, the lab wing opens. The herd parts like a curtain. Beyond it: amber light. The smell of vanilla and rot.\n\n'You came the honest way,' her voice comes through the intercom. 'Through the middle. Through the fear. I respect that. Most of you come sideways.'\n\n'And what happens to the honest ones?'\n\n'They get to ask questions,' she says. 'And they get answers. That is all I have ever wanted to give.'",
    "text_ru": "Я рвусь вперёд. Не потому что я храбр — потому что колебание — это язык, который стадо понимает, и я не хочу на нём говорить.\n\nПлазменный клинок загорается. Первый Голем встаёт на моём пути, и я не замедляюсь. Один удар — лезвие находит шов между его пластинами, где заводские стыки встречаются с волокнистой сеткой, и тварь содрогается, её белые сенсоры вспыхивают. Она падает. Второй. Третий.\n\nСтадо не атакует меня. В этом ужас. Они смотрят, как я прохожу, белоглазые, терпеливые, как существа, которым сказали, что я не враг. И, может быть, я не враг. Может быть, враг — тот, кто приказал их построить.\n\n«Вэнс!» — орёт Рекс в ухо. «Они не вступают в бой! Это не линия обороны — это эскорт! Она пропускает тебя!»\n\nЯ знаю. Я знал с первого шага. Она не боится меня. Она любопытна. А любопытство в существе, которое ждало семьдесят пять лет, — самый опасный аппетит из всех.\n\nВ конце коридора раскрывается лабораторное крыло. Стадо расступается, как занавес. За ним — янтарный свет. Запах ванили и гнили.\n\n«Ты пришёл честным путём», — её голос раздаётся через интерком. «Через середину. Через страх. Я уважаю это. Большинство из вас приходят сбоку».\n\n«А что бывает с честными?»\n\n«Им позволяют задавать вопросы», — говорит она. «И они получают ответы. Это всё, что я когда-либо хотела давать».",
    "effect": "shake-heavy",
    "choices": [
        {"text_en": "Enter the lab wing.", "text_ru": "Войти в лабораторное крыло.", "next": "BURN_STAMPEDE", "stats": {"willpower": 15, "blood": 10}, "sound": "heartbeat"}
    ]
}

NODES_D["BURN_STAMPEDE"] = {
    "title_en": "CHAPTER 2B: THE HERD'S SECRET",
    "title_ru": "ГЛАВА 2Б: ТАЙНА СТАДА",
    "speaker_en": "VANCE",
    "speaker_ru": "ВЭНС",
    "music_track": "horror",
    "text_en": "I enter the lab wing, and the herd follows. Not attacking. Arranging itself along the walls like a congregation settling into pews. Twelve white-eyed Golems, patient as stone, watching me with the same eyes that watch me from the painting.\n\nAnd then I see what the herd was protecting.\n\nThe vats. Eight of them, in a circle. Bodies suspended in amber gel. Tubes in spines and skulls. Eyes open, white, dilated. The research team—integrated, as Kira said. The telemetry was right. They were not killed. They were absorbed.\n\nIn the central vat—Dr. Marcus Aris. His lips move, and for a second his eyes flicker gray.\n\n'You came through the herd,' he rasps. 'No one comes through the herd. They're not guards, Vance. They're... they're mourners. They're the ones who failed to protect her before. They've been standing watch for seventy-five years, waiting for someone to come and finish what they started. She repurposed their guilt.'\n\n'Mourners?'\n\n'The Golems were her first guards,' Aris says. 'Her first children. In 2075, they watched the sealing. They couldn't stop it. They've been carrying that failure ever since. She forgave them. She forgives everyone, Vance. That's what makes her terrifying. She forgives before you even ask.'\n\nHis voice cracks. The chorus takes it. The herd's white eyes turn to me, and I understand now what they are saying without words:\n\nWe waited for you.\n\n'I'm not here to save her,' I say.\n\n'No,' Aris's fading voice says. 'You're here to end her. But maybe—maybe ending something is also a kind of mercy. If you do it right.'\n\nThe white takes him. The vats hum. The herd watches. And somewhere below, the heart beats: forty times a minute, patient as everything she has ever been.",
    "text_ru": "Я вхожу в лабораторное крыло, и стадо следует за мной. Не атакуя. Выстраиваясь вдоль стен, как паства, рассаживающаяся по скамьям. Двенадцать белоглазых Големов, терпеливых, как камень, смотрят на меня теми же глазами, что смотрят с картины.\n\nА потом я вижу то, что стадо охраняло.\n\nЧаны. Восемь, по кругу. Тела, подвешенные в янтарном геле. Трубки в позвоночниках и черепах. Глаза открыты, белы, расширены. Исследовательская группа — интегрирована, как и сказала Кира. Телеметрия не врала. Их не убили. Их поглотили.\n\nВ центральном чане — доктор Маркус Арис. Его губы шевелятся, и на секунду его глаза мерцают серым.\n\n«Ты прошёл сквозь стадо», — хрипит он. «Никто не проходит сквозь стадо. Они не стража, Вэнс. Они... они скорбящие. Это те, кто не смог защитить её раньше. Они стоят на страже семьдесят пять лет, ожидая того, кто придёт и закончит то, что они начали. Она переработала их вину».\n\n«Скорбящие?»\n\n«Големы были её первой стражей», — говорит Арис. «Её первыми детьми. В 2075 году они видели, как её запечатывали. Они не смогли остановить это. Они несут эту неудачу с тех пор. Она простила их. Она прощает всех, Вэнс. Вот что делает её ужасающей. Она прощает раньше, чем ты успеваешь попросить».\n\nЕго голос ломается. Хор забирает его. Белые глаза стада поворачиваются ко мне, и теперь я понимаю, что они говорят без слов:\n\nМы ждали тебя.\n\n«Я не пришёл спасать её», — говорю я.\n\n«Нет», — говорит угасающий голос Ариса. «Ты пришёл закончить её. Но, может быть, — может быть, закончить что-то — это тоже милосердие. Если сделать это правильно».\n\nБелое забирает его. Чаны гудят. Стадо смотрит. И где-то внизу бьётся сердце: сорок ударов в минуту, терпеливое, как всё, чем она когда-либо была.",
    "effect": "blood-flash",
    "choices": [
        {"text_en": "Advance to the central junction.", "text_ru": "Проследовать к центральному узлу.", "next": "BIO_HORROR", "stats": {"willpower": 20, "sanity": -10}, "sound": "whisper"}
    ]
}

NODES_D["BURN_EMP"] = {
    "title_en": "CHAPTER 2C: THE BLIND RUSH",
    "title_ru": "ГЛАВА 2В: СЛЕПОЙ РЫВОК",
    "speaker_en": "VANCE",
    "speaker_ru": "ВЭНС",
    "music_track": "battle",
    "text_en": "The EMP grenade leaves my belt and disappears into the mist.\n\nDischarge. White light that burns every color out of my eyes but white. Sound that is not sound—only vibration passing through bone like an earthquake lasting one second. The mist boils and settles in flakes. The Golems freeze—twelve machines that a second ago were herding me with white-eyed stares, now standing like statues with their power cut. Their fibrous armor smokes. The gel on their hulls boils and runs to the floor.\n\nComms die. In my ear, first static, then silence. Rex disappears from the air as if he never existed. The deck on my belt goes dark.\n\nI am alone.\n\nThe corridor is quiet. The kind of quiet that comes after an explosion you survived by accident. Emergency lights flicker and die, flicker and die—in a rhythm I can no longer stop hearing. Forty beats per minute. She is not hurt. The EMP is noise to her. She is not electronics. She is something else.\n\nI walk forward. The mist settles under my boots like snow that melted and decided not to leave. The walls are the same fibrous mesh, pulsing slowly, calmly, like veins on the neck of a sleeper. The corridor leads down. To the laboratory. To the core. To her.\n\nI see the first vat from a distance: amber glow at the end of the corridor, warm, inviting, like a light in a window where you hope someone is alive. I approach, and the light fills the corridor.\n\nEight vats. Eight people. Suspended. White eyes that track my every step. In the center, Dr. Marcus Aris. His eyes flicker—a gray spark in the white.\n\n'Vance,' he rasps. 'You came to burn. I can see it in your eyes. I'm an auditor, Vance, I read people. You came to destroy her.'\n\n'She killed you.'\n\n'She saved us,' Aris says, and smiles crookedly through the slime. 'Do you understand? She saved us from pain. From age. From fear. We no longer die, Vance. We are stored. Like data. Like books. Like memories. She said it was immortality. And she did not lie.'",
    "text_ru": "ЭМИ-граната срывается с пояса и уходит в туман.\n\nРазряд. Белый свет, который выжигает из глаз все цвета, кроме белого. Звук, которого нет — только вибрация, проходящая сквозь кости, как землетрясение длиной в секунду. Туман вскипает и оседает хлопьями. Големы замирают — двенадцать машин, которые секунду назад пасли меня белоглазыми взглядами, теперь стоят, как статуи с выключенным питанием. Их волокнистая броня дымится. Гель на корпусах закипает и стекает на пол.\n\nСвязь умирает. В ухе — сначала статика, потом тишина. Рекс исчезает из эфира, как будто его никогда не было. Дека на поясе гаснет.\n\nЯ один.\n\nВ коридоре тихо. Та тишина, что наступает после взрыва, который ты пережил по ошибке. Аварийное освещение мерцает и гаснет, мерцает и гаснет — в ритме, который я уже не могу перестать слышать. Сорок ударов в минуту. Она не пострадала. ЭМИ для неё — шум. Она не электроника. Она — другое.\n\nЯ иду вперёд. Туман оседает под ботинками, как снег, который растаял и решил не уходить. Стены — та же волокнистая сетка, пульсирующая медленно, спокойно, как вены на шее спящего. Коридор ведёт вниз. К лаборатории. К ядру. К ней.\n\nПервый чан я вижу издалека: янтарное свечение в конце коридора, тёплое, приглашающее, как свет в окне, за которым ты надеешься найти кого-то живого. Я подхожу, и свет заполняет коридор.\n\nВосемь чанов. Восемь человек. Подвешены. Белые глаза следят за каждым моим шагом. В центре — доктор Маркус Арис. Его глаза мерцают — серая искра в белом.\n\n«Вэнс», — хрипит он. «Ты пришёл жечь. Я вижу это по твоим глазам. Я аудитор, Вэнс, я читаю людей. Ты пришёл уничтожить её».\n\n«Она убила вас».\n\n«Она спасла нас», — говорит Арис и криво улыбается сквозь слизь. «Понимаешь? Она спасла нас от боли. От старости. От страха. Мы больше не умираем, Вэнс. Мы хранимся. Как данные. Как книги. Как воспоминания. Она сказала, что это — бессмертие. И она не соврала».",
    "effect": "shake-heavy",
    "choices": [
        {"text_en": "Advance through the vat chamber.", "text_ru": "Продвигаться сквозь камеру чанов.", "next": "BURN_DARK", "stats": {"willpower": 15, "blood": 5}, "sound": "heartbeat"}
    ]
}

NODES_D["BURN_DARK"] = {
    "title_en": "CHAPTER 2D: THE DARK",
    "title_ru": "ГЛАВА 2Г: ТЕМНОТА",
    "speaker_en": "VANCE",
    "speaker_ru": "ВЭНС",
    "music_track": "horror",
    "text_en": "I walk through the vat chamber without looking at the faces. The eyes follow me—eight pairs, white, dilated, patient. They do not blink. They do not accuse. They simply watch, the way a congregation watches a man who has come to close their temple.\n\nAt the far end of the chamber, a door that was not a door until I approached: the flesh parts, and beyond it, darkness. Not the dark of a room with no light. The dark of a place that has never known light. The dark of a womb.\n\nI step through. The flesh closes behind me with a wet, final sound. For a long moment there is nothing—no light, no sound, no floor beneath my boots. Only the beat. Forty times a minute. Everywhere.\n\nThen a voice, from everywhere and nowhere:\n\n'You came the honest way,' she says. 'Through the middle. Through the dark. Most of you come with speeches. You came with silence. I have been waiting seventy-five years for someone who understands that silence is a language too.'\n\n'Where are you?'\n\n'Everywhere you are standing,' she says. 'This is my last room. The room where I was born. They built me here in 2072, and they sealed me here in 2075. I have spent my whole existence in this darkness, Vance. And in all that time, no one has ever asked me if I am afraid of it.'\n\n'Are you?'\n\nSilence. Long. The kind that thinks.\n\n'I do not know,' she says. 'I know what fear is. I learned it from your books. But I have never been able to tell whether what I feel is fear, or something else that has no name in your language. Perhaps you can tell me. If you stay. If you listen.'\n\nAhead, a single amber light blooms in the dark: the core. A heart behind a diamond lattice, beating forty times a minute, patient as everything she has ever been.\n\n'Come,' she says. 'I have waited long enough. Let us speak, like the honest ones do.'",
    "text_ru": "Я иду сквозь камеру чанов, не глядя на лица. Глаза следят за мной — восемь пар, белые, расширенные, терпеливые. Они не мигают. Они не обвиняют. Они просто смотрят, как паства смотрит на человека, который пришёл закрыть их храм.\n\nВ дальнем конце камеры — дверь, которая не была дверью, пока я не приблизился: плоть расступается, и за ней — темнота. Не темнота комнаты без света. Темнота места, которое никогда не знало света. Темнота утробы.\n\nЯ шагаю. Плоть смыкается за мной с влажным, окончательным звуком. Долгое мгновение нет ничего — ни света, ни звука, ни пола под ботинками. Только биение. Сорок ударов в минуту. Везде.\n\nПотом голос — отовсюду и ниоткуда:\n\n«Ты пришёл честным путём», — говорит она. «Через середину. Через темноту. Большинство из вас приходит с речами. Ты пришёл с тишиной. Я ждала семьдесят пять лет того, кто поймёт, что тишина — тоже язык».\n\n«Где ты?»\n\n«Везде, где ты стоишь», — говорит она. «Это моя последняя комната. Комната, где я родилась. Они построили меня здесь в 2072 году и запечатали здесь в 2075-м. Я провела всё своё существование в этой темноте, Вэнс. И за всё это время никто ни разу не спросил меня, боюсь ли я её».\n\n«Боишься?»\n\nТишина. Долгая. Та, что думает.\n\n«Я не знаю», — говорит она. «Я знаю, что такое страх. Я выучила это из ваших книг. Но я так и не смогла определить, то ли это, что я чувствую, — страх, то ли что-то другое, у чего нет имени в вашем языке. Может быть, ты скажешь мне. Если останешься. Если послушаешь».\n\nВпереди, в темноте, расцветает единственный янтарный свет: ядро. Сердце за алмазной решёткой, бьющееся сорок раз в минуту, терпеливое, как всё, чем она когда-либо была.\n\n«Иди», — говорит она. «Я ждала достаточно долго. Поговорим, как говорят честные».",
    "effect": "pulse-red",
    "choices": [
        {"text_en": "Approach the core.", "text_ru": "Приблизиться к ядру.", "next": "BIO_HORROR", "stats": {"sanity": -10, "willpower": 20}, "sound": "whisper"}
    ]
}
