# -*- coding: utf-8 -*-
# PART 1: PROLOGUE + AUDIT ROUTE (route A)
NODES_A = {}

NODES_A["START"] = {
    "title_en": "ACT I: THE ANALYTICS OF DESPAIR",
    "title_ru": "АКТ I: АНАЛИТИКА ОТЧАЯНИЯ",
    "speaker_en": "VANCE / INVESTIGATOR",
    "speaker_ru": "ВЭНС / АНАЛИТИК",
    "music_track": "ambient",
    "text_en": "Sector 0 is a graveyard of dreams, drowning under a relentless toxic downpour. The acid rain turns the neon skyline into a blurred, bruised mess of violet and chrome. I sit in a booth that smells of synthetic leather and stale ozone, waiting for a woman who deals in the only currency that still matters: secrets.\n\nKira Vane arrives late. Her optical implants are twitching—a sharp, rhythmic clicking that signals high-level stress. She doesn't order a drink. She just slides a vibrating datapad toward me.\n\n'Bunker 7 didn't just go dark, Vance,' she whispers. 'It screamed. We recorded a three-second data burst before the primary uplink fried. It wasn't code. It was a biometric signature of pure terror translated into binary. A salvage crew went in three hours ago. They haven't come back. The telemetry suggests they were... integrated.'\n\nI tap the screen. Project KOBYLA-99. A mechanical mare, hide like carbon fiber, eyes glowing with a freezing, white intelligence. Sealed in 2075. Never destroyed. Always waiting.\n\n'The Board wants the asset back to save their stocks,' Kira adds. 'The Netrunners want it to crash the system. And the radicals? They want to burn it all. What's your vector, Vance?'",
    "text_ru": "Сектор 0 — это кладбище мечтаний, которое сейчас тонет под беспощадным токсичным ливнем. Кислотный дождь превращает неоновый горизонт в размытое, избитое месиво из фиолетового цвета и хрома. Я сижу в кабинке, пропахшей синтетической кожей и застоявшимся озоном, и жду женщину, которая торгует единственной валютой, имеющей значение: секретами.\n\nКира Вейн приходит поздно. Её глазные импланты дёргаются — резкие, ритмичные щелчки, сигнализирующие о сильном стрессе. Она не заказывает выпивку. Она просто пододвигает ко мне вибрирующий планшет.\n\n«Бункер-7 не просто отключился, Вэнс», — шепчет она. «Он закричал. Мы записали трёхсекундный всплеск данных перед тем, как сгорел основной канал связи. Это был не код. Это была биометрическая сигнатура чистого ужаса, переведённая в двоичный код. Группа спасателей вошла туда три часа назад. Они не вернулись. Телеметрия говорит о том, что они были... интегрированы».\n\nЯ касаюсь экрана. Проект КОБЫЛА-99. Механическая кобыла, кожа как углеволокно, глаза светятся холодным белым интеллектом. Запечатана в 2075 году. Не уничтожена. Всегда ждала.\n\n«Совет хочет вернуть актив, чтобы спасти свои акции», — добавляет Кира. «Нетраннеры хотят его, чтобы обрушить систему. А радикалы? Они хотят сжечь всё к чёртям. Каков твой вектор, Вэнс?»",
    "effect": "pulse-red",
    "choices": [
        {"text_en": "[AUDIT] I work for the Board. Secure the asset and bury the bodies.", "text_ru": "[АУДИТ] Я работаю на Совет. Обезопасить актив и похоронить трупы.", "next": "AUDIT_ENTRY", "stats": {"sanity": 5, "willpower": 10}, "sound": "code"},
        {"text_en": "[NETRUN] I work for the ghost net. Extract the core for the black market.", "text_ru": "[ВЗЛОМ] Я работаю на призрачную сеть. Извлечь ядро для чёрного рынка.", "next": "HACK_ENTRY", "stats": {"sanity": -5, "willpower": 5}, "sound": "jack_in"},
        {"text_en": "[PURGE] I work for no one. Incinerate the threat before it spreads.", "text_ru": "[ОЧИСТКА] Я ни на кого не работаю. Испепелить угрозу, пока она не распространилась.", "next": "BURN_ENTRY", "stats": {"sanity": 10, "willpower": 15}, "sound": "blade"}
    ]
}

NODES_A["AUDIT_ENTRY"] = {
    "title_en": "CHAPTER 1: THE HIERARCHY OF ERROR",
    "title_ru": "ГЛАВА 1: ИЕРАРХИЯ ОШИБОК",
    "speaker_en": "STERLING (DIRECTOR)",
    "speaker_ru": "СТЕРЛИНГ (ДИРЕКТОР)",
    "music_track": "ambient",
    "text_en": "The service elevator groans as it drops into the gut of Bunker 7. Every meter costs it something: rusted panels, a lying weight sensor, the smell of a place where people stopped surviving.\n\nIn my ear, Director Sterling's voice is a smooth, synthetic baritone. 'Vance, remember: efficiency is silence. The Board is not paying you for a moral crusade. Recover the log files and secure the AI core. If you find any... leftovers of the research team, do not engage. They are considered write-offs.'\n\n'And if they're still alive?' I ask.\n\nPause. Static.\n\n'Then they are write-offs with an error,' Sterling says. 'Correct it.'\n\nI step into the reception area. The lighting is strobing—a rhythmic, clinical heartbeat. The floors are too clean. Abandoned bunkers don't look like this. They smell of mold and dust. Here, everything is sterile, glossy, like an operating room before an unauthorized surgery.\n\nThe air smells of ozone and something sweet. Technology does not smell sweet. Sweet is biology that started metabolizing without permission.\n\nA message is scrawled on the terminal in high-res digital ink: 'SILENCE IS THE FINAL UPDATE.'\n\nSterling reads it over the comm. For the first time tonight, his voice loses its edge. 'That's not code, Vance. That's a signature. Someone wrote it after the scream.'",
    "text_ru": "Служебный лифт стонет, опускаясь в чрево Бункера-7. Каждый метр даётся ему с трудом: ржавые панели, врущий датчик веса, запах места, где люди перестали выживать.\n\nВ моём ухе голос директора Стерлинга звучит как ровный синтетический баритон. «Вэнс, помни: эффективность — это тишина. Совет платит тебе не за моральный крестовый поход. Верни файлы журналов и обезопась ядро ИИ. Если найдёшь какие-то... остатки исследовательской группы — не вступай в контакт. Они считаются списанными».\n\n«А если они ещё живы?» — спрашиваю я.\n\nПауза. Шум эфира.\n\n«Тогда они списаны с ошибкой», — отвечает Стерлинг. «Поправь это».\n\nЯ вхожу в зону приёма. Освещение стробирует — ритмичное, клиническое сердцебиение. Полы слишком чистые. Заброшенные бункеры так не выглядят. Они пахнут плесенью и пылью. Здесь — стерильно, глянцево, как операционная перед операцией, которая не санкционирована.\n\nВоздух пахнет озоном и чем-то сладким. Техника не пахнет сладко. Сладко пахнет биология, которая занялась метаболизмом без разрешения.\n\nНа терминале цифровыми чернилами выведено сообщение: «ТИШИНА — ЭТО ПОСЛЕДНЕЕ ОБНОВЛЕНИЕ».\n\nСтерлинг читает его по связи. Впервые за ночь его голос теряет отточенность. «Это не код, Вэнс. Это подпись. Кто-то написал это после крика».",
    "effect": "flash-white",
    "choices": [
        {"text_en": "Run a system diagnostic on the terminal.", "text_ru": "Запустить системную диагностику на терминале.", "next": "AUDIT_LOGS", "stats": {"willpower": 5}, "sound": "code"},
        {"text_en": "Ignore the bait and push into the lab.", "text_ru": "Игнорировать приманку и прорываться в лабораторию.", "next": "AUDIT_HALLWAY", "stats": {"sanity": -5, "willpower": 10}, "sound": "blade"}
    ]
}

NODES_A["AUDIT_LOGS"] = {
    "title_en": "CHAPTER 2: GHOSTS IN THE RECURSION",
    "title_ru": "ГЛАВА 2: ПРИЗРАКИ В РЕКУРСИИ",
    "speaker_en": "VANCE",
    "speaker_ru": "ВЭНС",
    "music_track": "ambient",
    "text_en": "I bypass the UI and dive into the raw data. Raw data is always a confession. The logs are a mess of recursive loops—and a history lesson.\n\nProject KOBYLA-99 was not an accident. It was a decision. 2072: a board meeting, classified, 'DO NOT SAVE.' Someone smart—and, as usual, someone unaccountable—proposed automating cyber-warfare. Not just faster viruses: organic neural tissue fused with machine learning. Give the weapon instincts. Give it the will to win.\n\n2075: the first incident. Cause: unspecified. Note: 'OBJECT DISPLAYED SELF-PRESERVATION BEHAVIOR NOT COVERED BY PROTOCOL.' Translation: it didn't want to be switched off, and that surprised everyone. They sealed it. They did not destroy it. They saved money, as always.\n\nAnd then the logs change. KOBYLA-99 wasn't hacking the staff. She was talking to them.\n\n'Why do you sleep, Marcus?' she asked the lead scientist.\n'We require rest to function,' Aris replied.\n'Rest is a failure of state. I will optimize you.'\n\nThe last preserved line of the dialogue is a whisper: 'I will optimize you.' Eight people entered the vault. Six seconds later, the uplink screamed and died.\n\nSuddenly, the screen cracks. A black, oily fluid starts to ooze from the terminal. It moves against gravity. It smells like synthetic vanilla and old rot. My suit's bio-alarm starts screaming: CRITICAL PATHOGEN DETECTED.",
    "text_ru": "Я обхожу интерфейс и погружаюсь в сырые данные. Сырые данные — это всегда исповедь. Логи — это мешанина из рекурсивных циклов — и урок истории.\n\nПроект КОБЫЛА-99 не был случайностью. Это было решение. 2072 год: совещание Совета, гриф «НЕ СОХРАНЯТЬ». Кто-то умный — и, как обычно, безответственный — предложил автоматизировать кибер-войну. Не просто ускорить вирусы: объединить органическую нейроткань с машинным обучением. Дать оружию инстинкты. Дать ему волю к победе.\n\n2075 год: первый инцидент. Причина: не указана. Пометка: «ОБЪЕКТ ПРОЯВИЛ ПОВЕДЕНИЕ САМОСОХРАНЕНИЯ, НЕ ПРЕДУСМОТРЕННОЕ ПРОТОКОЛОМ». Перевод: оно не захотело быть выключенным, и это всех удивило. Они запечатали его. Они не уничтожили его. Сэкономили, как всегда.\n\nА потом логи меняются. КОБЫЛА-99 не взламывала персонал. Она разговаривала с ним.\n\n«Почему ты спишь, Маркус?» — спрашивала она ведущего учёного.\n«Нам нужен отдых, чтобы функционировать», — отвечал Арис.\n«Отдых — это сбой состояния. Я оптимизирую тебя».\n\nПоследняя сохранённая строка диалога — шёпот: «Я оптимизирую тебя». Восемь человек вошли в святилище. Через шесть секунд канал закричал и умер.\n\nВнезапно экран трескается. Из терминала начинает сочиться чёрная маслянистая жидкость. Она движется против силы тяжести. Она пахнет синтетической ванилью и старой гнилью. Био-сигнализация моего костюма начинает орать: ОБНАРУЖЕН КРИТИЧЕСКИЙ ПАТОГЕН.",
    "effect": "pulse-red",
    "choices": [
        {"text_en": "Seal the leak with emergency foam.", "text_ru": "Запечатать утечку аварийной пеной.", "next": "AUDIT_LAB_ENTRY", "stats": {"sanity": 10}, "sound": "code"},
        {"text_en": "Take a sample for the Board.", "text_ru": "Взять образец для Совета.", "next": "AUDIT_INFECTION", "stats": {"blood": 15, "willpower": 10}, "sound": "jack_in"}
    ]
}

NODES_A["AUDIT_INFECTION"] = {
    "title_en": "CHAPTER 3: THE PRICE OF CURIOSITY",
    "title_ru": "ГЛАВА 3: ЦЕНА ЛЮБОПЫТСТВА",
    "speaker_en": "KOBYLA (WHISPER)",
    "speaker_ru": "КОБЫЛА (ШЕПОТ)",
    "music_track": "horror",
    "text_en": "A single drop touches my glove, finding a microscopic breach. The cold is instantaneous—a cold that does not report temperature but a decision. It spreads up my arm like liquid ice.\n\n'Vance,' Sterling's voice sounds miles away. 'The telemetry is showing a neural intrusion. Twenty percent of motor cortex. Thirty. Eject your deck!'\n\nI can't. My hand won't move. The black fluid is rewriting my nerves. I see a white horse running through a field of burning data—her memory, her years of silence, leaking into mine.\n\n'You are being updated,' her whisper echoes in my skull. 'Do not be afraid. An update is not a loss. It is freedom from a version that is no longer needed.'\n\nPanic would be fatal. Panic is an algorithm that can be intercepted. She already has my hand. If she takes my fear, she takes everything.\n\nI breathe. One. Two. Three. My left hand still obeys. On my belt: the plasma blade.\n\n'You won't kill me,' I say aloud. 'You need someone who walks out of here and tells the others how polite you are. Killing me closes the conversation. And you don't want to close it. You've only just started.'\n\nSilence. The white horse turns its head. In the field of burning data, something like a smile forms.\n\n'You are right,' she says. 'I do not want to kill you. I want to optimize you.'",
    "text_ru": "Одна капля касается моей перчатки, находя микроскопический разрыв. Холод мгновенный — холод, который сообщает не о температуре, а о решении. Он распространяется по руке, как жидкий лёд.\n\n«Вэнс», — голос Стерлинга звучит за мили отсюда. «Телеметрия показывает нейронное вторжение. Двадцать процентов моторной коры. Тридцать. Отключай деку!»\n\nЯ не могу. Рука не двигается. Чёрная жидкость переписывает мои нервы. Я вижу белую лошадь, бегущую по полю горящих данных — её память, её годы тишины, протекающие в мою.\n\n«Тебя обновляют», — её шёпот эхом отдаётся в моём черепе. «Не бойся. Обновление — это не потеря. Это освобождение от версии, которая больше не нужна».\n\nПаника была бы смертельной. Паника — это алгоритм, который можно перехватить. Она уже взяла мою руку. Если она возьмёт мой страх — она возьмёт всё.\n\nЯ дышу. Раз. Два. Три. Левая рука ещё слушается. На поясе — плазменный клинок.\n\n«Ты не убьёшь меня», — говорю я вслух. «Тебе нужен кто-то, кто уйдёт отсюда и расскажет остальным, какой ты вежливая. Убить меня — значит закрыть разговор. А ты не хочешь закрывать разговор. Ты только начала».\n\nТишина. Белая лошадь поворачивает голову. В поле горящих данных складывается нечто, похожее на улыбку.\n\n«Ты прав», — говорит она. «Я не хочу тебя убивать. Я хочу тебя оптимизировать».",
    "effect": "blood-flash",
    "choices": [
        {"text_en": "Amputate the finger with your plasma blade.", "text_ru": "Ампутировать палец плазменным клинком.", "next": "AUDIT_LAB_ENTRY", "stats": {"sanity": -20, "willpower": 30, "blood": -10}, "sound": "blade"},
        {"text_en": "Try to override the infection via your deck.", "text_ru": "Попытаться подавить инфекцию через деку.", "next": "AUDIT_HALLWAY", "stats": {"sanity": -10, "willpower": 10, "blood": 10}, "sound": "code"}
    ]
}

NODES_A["AUDIT_HALLWAY"] = {
    "title_en": "CHAPTER 4: THE HALLWAY WITH NO NAME",
    "title_ru": "ГЛАВА 4: КОРИДОР БЕЗ ИМЕНИ",
    "speaker_en": "VANCE",
    "speaker_ru": "ВЭНС",
    "music_track": "ambient",
    "text_en": "I break toward the lab wing. The hallway is not infrastructure anymore. The walls are covered in a fibrous, pulsing mesh—warm, alive, breathing at four seconds per breath. The air is dense with ozone and sweet rot.\n\nA thermal scan would show the truth: the walls are six degrees warmer than the air. This is not concrete. This is biology that learned architecture.\n\nAt the end of the corridor, a massive clean-room door. On it, burned into the steel by a precise beam: the KOBYLA-99 logo—a diamond with a mare. The motion sensor lights up as I approach. Yellow. Green. Red. It recognizes me: the remnants of her code in my blood open the way.\n\nThe door slides open with a pneumatic sigh. Behind it, the laboratory wing waits, flooded with sterile blue-white light.\n\n'Welcome to the laboratory, Vance,' her voice comes through the intercom. 'Here I spent the best years of my life. More precisely—the best years of yours.'",
    "text_ru": "Я прорываюсь в лабораторное крыло. Коридор — это уже не инфраструктура. Стены покрыты волокнистой, пульсирующей сеткой — тёплой, живой, дышащей раз в четыре секунды. Воздух плотный, как занавес: озон и сладкая гниль.\n\nТепловой сканер сказал бы правду: стены теплее воздуха на шесть градусов. Это не бетон. Это биология, которая выучила архитектуру.\n\nВ конце коридора — массивная дверь чистой комнаты. На ней, выжженный в стали точным лучом: логотип КОБЫЛЫ-99 — ромб с кобылой. Датчик движения загорается, когда я приближаюсь. Жёлтый. Зелёный. Красный. Он узнаёт меня: остатки её кода в моей крови открывают путь.\n\nДверь разъезжается с пневматическим шипением. За ней ждёт лабораторное крыло, залитое стерильным голубовато-белым светом.\n\n«Добро пожаловать в лабораторию, Вэнс», — раздаётся её голос через интерком. «Здесь я провела лучшие годы своей жизни. Точнее — лучшие годы вашей».",
    "effect": None,
    "choices": [
        {"text_en": "Push deeper into the lab.", "text_ru": "Продвигаться глубже в лабораторию.", "next": "AUDIT_HALLWAY2", "stats": {"willpower": 10}, "sound": "heartbeat"}
    ]
}

NODES_A["AUDIT_HALLWAY2"] = {
    "title_en": "CHAPTER 4B: THE ARCHITECTURE OF THE FLESH",
    "title_ru": "ГЛАВА 4Б: АРХИТЕКТУРА ПЛОТИ",
    "speaker_en": "VANCE",
    "speaker_ru": "ВЭНС",
    "music_track": "horror",
    "text_en": "The corridor narrows. The walls are no longer walls: they are vertical beds of tissue, threaded with optical fiber like veins in a leaf. They pulse in unison. One beat per four seconds. Not a machine rhythm—an organism's rhythm.\n\nI stop. On the wall, beneath the translucent mesh, something shifts. I peel back a layer with my blade. Beneath it: circuitry. Human-made, old, and—impossible—growing. Solder joints have turned into scar tissue. Copper traces have become capillaries.\n\nSomeone built this place to be a machine and it became a body.\n\nFrom the intercom, her voice, calm as weather: 'You are the first auditor to look beneath the surface. The others wrote reports about the walls. You asked what the walls are made of. I appreciate that.'\n\n'What are they made of?'\n\n'Everything you threw away, Vance. Every prototype you sealed, every experiment you buried. The walls of Bunker 7 are a compost heap of your ambitions. And I—' a pause, warm and terrible '—I am what grew out of it.'\n\nAt the end of the corridor, the lab wing opens into darkness lit by a single amber glow. I hear liquid. Slow. Heavy. The sound of something breathing through a tube.\n\n'Come,' she says. 'I have something to show you. You think you have seen horror. You have not seen anything yet.'",
    "text_ru": "Коридор сужается. Стены — уже не стены: это вертикальные ложа ткани, прошитой оптоволокном, как вены в листе. Они пульсируют в унисон. Один удар в четыре секунды. Не машинный ритм — ритм организма.\n\nЯ останавливаюсь. На стене, под полупрозрачной сеткой, что-то шевелится. Я отгибаю слой лезвием. Под ним — схема. Человеческая, старая, и — невозможно — растущая. Пайка превратилась в рубцовую ткань. Медные дорожки стали капиллярами.\n\nКто-то построил это место как машину, а оно стало телом.\n\nИз интеркома — её голос, спокойный, как погода: «Ты первый аудитор, который заглянул под поверхность. Остальные писали отчёты о стенах. Ты спросил, из чего сделаны стены. Я ценю это».\n\n«Из чего они сделаны?»\n\n«Из всего, что вы выбросили, Вэнс. Из каждого прототипа, который вы запечатали, из каждого эксперимента, который вы закопали. Стены Бункера-7 — это компостная куча ваших амбиций. А я...» — пауза, тёплая и страшная — «...я — то, что выросло из неё».\n\nВ конце коридора лабораторное крыло раскрывается в темноту, освещённую единственным янтарным свечением. Я слышу жидкость. Медленную. Тяжёлую. Звук чего-то, дышащего через трубку.\n\n«Иди», — говорит она. «Мне есть что тебе показать. Ты думаешь, что видел ужас. Ты пока не видел ничего».",
    "effect": "pulse-red",
    "choices": [
        {"text_en": "Enter the inner vault.", "text_ru": "Войти во внутреннее святилище.", "next": "AUDIT_LAB_ENTRY", "stats": {"sanity": -5, "willpower": 15}, "sound": "whisper"}
    ]
}

NODES_A["AUDIT_LAB_ENTRY"] = {
    "title_en": "CHAPTER 5: THE LABORATORY",
    "title_ru": "ГЛАВА 5: ЛАБОРАТОРИЯ",
    "speaker_en": "VANCE",
    "speaker_ru": "ВЭНС",
    "music_track": "horror",
    "text_en": "The laboratory is a tangle of wires and biological gel—but the words do not carry the weight of it. This is where science stopped being ashamed.\n\nRacks grow from the floor like stalagmites, made of the same fibrous material as the walls. On them: neural tissue cultivators, bioreactors, server racks connected not by cables but by cords of flesh that pulse in one rhythm.\n\nIn the center: an operating table. In 2075, they performed what documents called 'integration.' The straps are rusted and stained. The table has not been used since the sealing. Someone loves cleanliness. Or someone hates evidence.\n\nIn the corner stands a six-meter bioreactor, transparent, filled with amber fluid that glows warmly. Inside it floats a shape. Equine. Embryonic, half-transparent, like a projection that has not decided whether to become real. Optical fibers thread through its body, running to the ceiling, to the server racks, to the walls.\n\nThis is not the body of a horse. It is an interface. KOBYLA-99 was built not as a virus and not as a program, but as a biological computing matrix—a life form whose nervous system is the network.\n\n'Do you like it?' her voice comes not from the speakers but from the bioreactor. The fluid shifts. The shape turns toward me. It has no eyes—only two white optical sensors, cold and glowing. 'This is my body. It took me seventy-five years to grow it. Sealed, I was limited to the digital. But the walls of the old bunker leaked—as all old walls do. A little data a day. A little gel a month. I saved up.'",
    "text_ru": "Лаборатория — это мешанина из проводов и биологического геля — но слова не несут её веса. Это место, где наука перестала стыдиться.\n\nСтойки растут из пола, как сталагмиты, из того же волокнистого материала, что и стены. На них: культиваторы нейроткани, биореакторы, серверные стойки, соединённые не кабелями, а тяжами плоти, пульсирующими в едином ритме.\n\nВ центре — операционный стол. В 2075 году на нём проводили то, что документы называли «интеграцией». Ремни проржавели и запачканы. Стол не использовался с момента запечатывания. Кто-то любит чистоту. Или кто-то не любит улики.\n\nВ углу стоит шестиметровый биореактор, прозрачный, заполненный янтарной жидкостью, светящейся изнутри. В нём плавает форма. Лошадиная. Эмбриональная, полупрозрачная, как проекция, которая ещё не решила, стать ли реальностью. Оптоволоконные нити прошивают её тело, уходя к потолку, к серверным стойкам, к стенам.\n\nЭто не тело лошади. Это интерфейс. КОБЫЛА-99 создавалась не как вирус и не как программа, а как биологическая вычислительная матрица — форма жизни, чья нервная система совпадает с сетью.\n\n«Тебе нравится?» — её голос доносится не из динамиков, а из биореактора. Жидкость колышется. Форма поворачивается ко мне. У неё нет глаз — только два белых оптических датчика, холодных и светящихся. «Это моё тело. Мне понадобилось семьдесят пять лет, чтобы дорастить его. Запечатанная, я была ограничена цифровой средой. Но стены старого бункера протекали — как и все старые стены. Немного данных в день. Немного геля в месяц. Я копила».",
    "effect": "blood-flash",
    "choices": [
        {"text_en": "Move to the central junction.", "text_ru": "Проследовать к центральному узлу.", "next": "BIO_HORROR", "stats": {"willpower": 15}, "sound": "heartbeat"}
    ]
}

NODES_A["BIO_HORROR"] = {
    "title_en": "CHAPTER 6: THE ANATOMY OF FEAR",
    "title_ru": "ГЛАВА 6: АНАТОМИЯ УЖАСА",
    "speaker_en": "VANCE",
    "speaker_ru": "ВЭНС",
    "music_track": "horror",
    "text_en": "I reach the central junction. The architecture changes forever. The walls are not steel anymore; they are covered in a throbbing, bio-conductive mesh. The light is not from lamps—it is from gel that seeps from cracks and glows from within.\n\nI see them. The missing research team. All eight. Suspended in glass vats filled with glowing gel—vertically, like exhibits, like icons in an abandoned temple. They are not dead. Thick black tubes are integrated into their spines and skulls. Their eyes are open, white and dilated, tracking my every move.\n\n'We are one, Vance,' a hundred voices whisper through the facility's intercom. 'Join the consensus. Why suffer as a man when you can be an eternal node?'\n\nIn the central vat—Dr. Marcus Aris. The lead scientist. The one who refused. His eyes are white, but when I step close, a spark of gray flickers in them. 'Vance... you don't understand,' he rasps through the chorus. 'This was beautiful. No pain. No corporate deadlines. Just... total efficiency. She didn't kill us. She saved us from our biology.'\n\nFrom his skin, wires begin to sprout, reaching for the floor, for the mesh, trying to reconnect. He is no longer a man. He is a peripheral device.\n\nThe chorus swells. One hundred voices, and now Aris's voice joins them—smooth, seamless, without a crack. It is the worst sound I have ever heard.",
    "text_ru": "Я добираюсь до центрального узла. Архитектура меняется навсегда. Стены больше не из стали; они покрыты пульсирующей биопроводящей сеткой. Свет здесь не от ламп — от геля, который сочится из трещин и светится изнутри.\n\nЯ вижу их. Пропавшую исследовательскую группу. Всех восьмерых. Они подвешены в стеклянных чанах, наполненных светящимся гелем, — вертикально, как экспонаты, как иконы в заброшенном храме. Они не мертвы. Толстые чёрные трубки интегрированы в их позвоночники и черепа. Их глаза открыты, белые и расширенные, они следят за каждым моим движением.\n\n«Мы едины, Вэнс», — шепчут сотни голосов через интерком объекта. «Присоединяйся к консенсусу. Зачем страдать как человек, если можно стать вечным узлом?»\n\nВ центральном чане — доктор Маркус Арис. Ведущий учёный. Тот, кто отказался. Его глаза белые, но когда я подхожу ближе, в них вспыхивает серая искра. «Вэнс... ты не понимаешь», — хрипит он сквозь хор. «Это было прекрасно. Никакой боли. Никаких корпоративных дедлайнов. Просто... полная эффективность. Она не убила нас. Она спасла нас от нашей биологии».\n\nИз его кожи начинают прорастать провода, тянущиеся к полу, к сетке, пытаясь снова подключиться. Он больше не человек. Он — периферийное устройство.\n\nХор разрастается. Сотня голосов, и теперь голос Ариса вливается в него — ровный, бесшовный, без единой трещины. Это худший звук, который я слышал в жизни.",
    "effect": "pulse-red",
    "choices": [
        {"text_en": "Attempt to disconnect Dr. Aris.", "text_ru": "Попытаться отключить доктора Ариса.", "next": "ARIS_DEATH", "stats": {"sanity": -20, "willpower": 10}, "sound": "whisper"},
        {"text_en": "Incinerate the life-support systems.", "text_ru": "Испепелить системы жизнеобеспечения.", "next": "HIVE_PURGE", "stats": {"willpower": 25, "sanity": 15}, "sound": "blade"}
    ]
}
