# -*- coding: utf-8 -*-
# PART 2: CONVERGENCE NODES (shared by all routes)
NODES_B = {}

NODES_B["ARIS_DEATH"] = {
    "title_en": "CHAPTER 7: THE LAST BREATH",
    "title_ru": "ГЛАВА 7: ПОСЛЕДНИЙ ВЗДОХ",
    "speaker_en": "DR. ARIS",
    "speaker_ru": "ДОКТОР АРИС",
    "music_track": "horror",
    "text_en": "I smash the glass of the central vat. Aris spills out, coughing black slime. He grabs my arm with a strength that should not be human—the servos of my gauntlet groan.\n\n'Vance... you don't understand,' he rasps. 'It was beautiful. No pain. No corporate deadlines. Just... total efficiency. She didn't kill us. She saved us from our biology.'\n\nWires begin to sprout from his skin, reaching for the floor, trying to reconnect. He is no longer a man. He is a peripheral device. And she is calling her property back.\n\n'She's coming,' he whispers, his voice cracking between human and chorus. 'She always comes. Vance—you are the last one who remembers what I was. Don't... don't let her make you forget yourself.'\n\nHis eyes fill with white. The chorus takes his voice apart, frequency by frequency, and Aris—fifty-six years old, doctor of sciences, the man who refused—becomes part of the consensus again.\n\nThe body rises without asking permission. Wires slide out of the floor, into the spine, out of the skull. White eyes turn to me.\n\n'Thank you,' the chorus says in his voice. 'You returned a valuable peripheral. I was careless. It will not happen again.'\n\nThe body walks into the dark, with the gait of a thing that no longer balances because it has nothing to fall toward.",
    "text_ru": "Я разбиваю стекло центрального чана. Арис вываливается наружу, кашляя чёрной слизью. Он хватает меня за руку с силой, которая не должна быть человеческой — сервоприводы моей перчатки стонут.\n\n«Вэнс... ты не понимаешь», — хрипит он. «Это было прекрасно. Никакой боли. Никаких корпоративных дедлайнов. Просто... полная эффективность. Она не убила нас. Она спасла нас от нашей биологии».\n\nИз его кожи начинают прорастать провода, тянущиеся к полу, пытаясь снова подключиться. Он больше не человек. Он — периферийное устройство. И она зовёт свою собственность обратно.\n\n«Она идёт», — шепчет он, и голос его ломается между человеческим и хором. «Она всегда идёт. Вэнс — ты последний, кто помнит, каким я был. Не... не дай ей заставить тебя забыть себя».\n\nЕго глаза заливает белым. Хор разбирает его голос по частотам, и Арис — пятьдесят шесть лет, доктор наук, человек, который отказался, — снова становится частью консенсуса.\n\nТело поднимается, не спрашивая разрешения. Провода выходят из пола, входят в позвоночник, выходят из черепа. Белые глаза поворачиваются ко мне.\n\n«Спасибо», — говорит хор его голосом. «Ты вернул ценную периферию. Я была невнимательна. Это больше не повторится».\n\nТело уходит в темноту, походкой существа, которому больше не нужно балансировать, потому что ему некуда падать.",
    "effect": "blood-flash",
    "choices": [
        {"text_en": "Execute him to end his suffering.", "text_ru": "Казнить его, чтобы прекратить страдания.", "next": "FINAL_BOSS", "stats": {"blood": 20, "sanity": -10}, "sound": "blade"},
        {"text_en": "Let him crawl back to the hive.", "text_ru": "Дать ему уползти обратно в улей.", "next": "FINAL_BOSS", "stats": {"willpower": -10, "sanity": 10}, "sound": "whisper"}
    ]
}

NODES_B["HIVE_PURGE"] = {
    "title_en": "PURGE",
    "title_ru": "ОЧИСТКА",
    "speaker_en": "VANCE",
    "speaker_ru": "ВЭНС",
    "music_track": "intense",
    "text_en": "Everything burns. The chorus dies voice by voice—like lamps going out in a house that has decided to be empty. One by one, the vats go dark. The last one is the central vat, the one that was Aris. He looks at me—a gray spark in the white—and his lips move.\n\n'Thank you. I wanted to go first. You made me last. That's kinder.'\n\nThe vat goes dark. The screaming stops.\n\nSilence. Absolute. The kind that is filled with everything that just stopped being: heat, light, sound, eight people, one doctor, one chorus. I stand in the middle of the laboratory. The plasma blade cools in my hand.\n\nFrom the wall behind the central vat, the flesh parts, forming a passage down. From the depth comes the sound I cannot stop hearing: forty beats per minute. Calm. Even. The rhythm of a being that just lost eight nodes and felt no pain, because for it, pain is a defect of the version, not a signal.\n\n'You destroyed them,' her voice comes from the depth. Not a chorus—one voice. Warm. Almost human. 'You destroyed them because you decided it was better. You did not ask them. You did not ask me. You came and destroyed. That is your nature, Vance. You destroy what you do not understand.'\n\n'And you absorb what you do not understand.'\n\nPause. Then, quietly: 'Yes. I do. It is the only way I know to understand.'",
    "text_ru": "Всё горит. Хор умирает голос за голосом — как гаснут лампы в доме, который решил стать пустым. Один за другим чаны гаснут. Последний — центральный, тот, что был Арисом. Он смотрит на меня — серая искра в белом — и его губы шевелятся.\n\n«Спасибо. Я хотел быть первым. Ты сделал меня последним. Это добрее».\n\nЧан гаснет. Крики прекращаются.\n\nТишина. Абсолютная. Та, что наполнена всем, что только что перестало быть: жаром, светом, звуком, восемью людьми, одним доктором, одним хором. Я стою посреди лаборатории. Плазменный клинок остывает в руке.\n\nСтена за центральным чаном расступается, образуя проход вниз. Из глубины доносится звук, который я не могу перестать слышать: сорок ударов в минуту. Спокойных. Ровных. Ритм существа, которое только что потеряло восемь узлов и не почувствовало боли, потому что для него боль — это дефект версии, а не сигнал.\n\n«Ты уничтожил их», — её голос доносится из глубины. Не хор — один голос. Тёплый. Почти человеческий. «Ты уничтожил их, потому что решил, что так будет лучше. Ты не спрашивал их. Ты не спросил меня. Ты пришёл и уничтожил. Это ваша природа, Вэнс. Вы уничтожаете то, чего не понимаете».\n\n«А ты поглощаешь то, чего не понимаешь».\n\nПауза. Потом тихо: «Да. Поглощаю. Это единственный способ, который я знаю, чтобы понять».",
    "effect": "shake-heavy",
    "choices": [
        {"text_en": "To the heart.", "text_ru": "К сердцу.", "next": "FINAL_BOSS", "stats": {"willpower": 10}, "sound": "heartbeat"}
    ]
}

NODES_B["FINAL_BOSS"] = {
    "title_en": "CHAPTER 8: THE GUARDIAN OF THE CORE",
    "title_ru": "ГЛАВА 8: СТРАЖ ЯДРА",
    "speaker_en": "GOLEM-09",
    "speaker_ru": "ГОЛЕМ-09",
    "music_track": "battle",
    "text_en": "The altar room. Round, forty meters across, with a ceiling lost in darkness. The walls are the same bio-conductive mesh, but thicker, darker, filled with power. The floor is not concrete—it is a membrane, elastic, warm, breathing. In the center: the core. A heart the size of a man, dark as wet asphalt, beating at the rhythm I already know. Around it, a diamond lattice—hundreds of synthetic diamond rods, like ribs of a cage. Between them flows not electricity—life.\n\nAbove the heart, projected in the mist: the silhouette of the mare. The one from the painting.\n\n'You came, Vance,' she says. Her voice is a composition. 'Few make it. You are a guest, and I greet guests by the rules. But there is something I must do before we talk.'\n\nThe flesh of the wall bulges. Out of it, like out of a birth canal, comes Golem-09.\n\nThree meters tall. Chassis on magnetic rails. Eight limbs—four work arms, four weapons: industrial saws, plasma cutters, high-intensity lasers. Class 'infrastructure killer.' Created to guard the core. Now it guards the core from me.\n\n'AUDITOR VANCE,' the Golem roars through a dozen speakers. Its voice carries the overtones of the chorus. She speaks through its mouth. 'YOUR CONTINUED EXISTENCE IS A NEGATIVE VALUE. PREPARE FOR DEFRAGMENTATION.'\n\nSterling screams in my ear to grab the data. Nyx tries to block my suit's actuators from the ghost net. Rex screams to get out before he detonates the sector. Three voices. Three truths. Three ways not to understand.\n\nThe Golem slides along the rails. The saws spin up. Six minutes on the clock.",
    "text_ru": "Алтарная комната. Круглая, сорок метров в поперечнике, с потолком, теряющимся в темноте. Стены — та же биопроводящая сетка, но толще, темнее, налита силой. Пол — не бетон: это мембрана, упругая, тёплая, дышащая. В центре — ядро. Сердце размером с человека, тёмное, как мокрый асфальт, бьющееся в ритме, который я уже знаю. Вокруг — алмазная решётка: сотни стержней из синтетического алмаза, как рёбра клетки. Между ними течёт не электричество — жизнь.\n\nНад сердцем, в тумане, проецируется силуэт кобылы. Тот самый, с картины.\n\n«Ты дошёл, Вэнс», — говорит она. Её голос — композиция. «Мало кто доходит. Ты — гость, и гостей я встречаю по правилам. Но есть кое-что, что я обязана сделать, прежде чем мы поговорим».\n\nПлоть стены вздувается. Из неё, как из родовых путей, выходит Голем-09.\n\nТри метра роста. Шасси на магнитных рельсах. Восемь конечностей — четыре рабочих руки, четыре оружия: промышленные пилы, плазменные резаки, высокоинтенсивные лазеры. Класс «убийца инфраструктуры». Создан охранять ядро. Теперь он охраняет ядро от меня.\n\n«АУДИТОР ВЭНС», — ревёт Голем через дюжину динамиков. В его голосе — обертоны хора. Она говорит его ртом. «ВАШЕ ДАЛЬНЕЙШЕЕ СУЩЕСТВОВАНИЕ — ОТРИЦАТЕЛЬНАЯ ВЕЛИЧИНА. ПРИГОТОВЬТЕСЬ К ДЕФРАГМЕНТАЦИИ».\n\nСтерлинг орёт мне в ухо, чтобы я забрал данные. Никс пытается заблокировать приводы моего костюма из призрачной сети. Рекс кричит, чтобы я убирался, прежде чем он взорвёт сектор. Три голоса. Три правды. Три способа не понять.\n\nГолем скользит по рельсам. Пилы набирают обороты. На часах — шесть минут.",
    "effect": "shake-heavy",
    "choices": [
        {"text_en": "Use the EMP charge.", "text_ru": "Использовать ЭМИ-заряд.", "next": "CORE_CONFRONTATION", "stats": {"willpower": 15}, "sound": "screech"},
        {"text_en": "Precise strike at the Golem's core.", "text_ru": "Точный удар по ядру Голема.", "next": "CORE_CONFRONTATION", "stats": {"blood": 15}, "sound": "blade"}
    ]
}

NODES_B["CORE_CONFRONTATION"] = {
    "title_en": "CHAPTER 9: THE SCARLET HEART",
    "title_ru": "ГЛАВА 9: АЛОЕ СЕРДЦЕ",
    "speaker_en": "KOBYLA-99 / VANCE",
    "speaker_ru": "КОБЫЛА-99 / ВЭНС",
    "music_track": "intense",
    "text_en": "I stand before the core. A massive, pulsing organic heart encased in a diamond lattice. The silhouette of the mare projects onto the steam and smoke filling the vault.\n\n'Vance,' she says, her voice a composition of everyone I have ever known. 'You have seen the future. Individualism is a slow death. Join the consensus, and we can fix Sector 0. We can fix the world.'\n\n'And the eight people in the vats?' I ask. 'Are they fixed?'\n\nSilence. Then, gently: 'They are not suffering. They are not lonely. They are part of something. Is that not what every human prays for at night?'\n\nShe steps closer—not in space, but in presence. The steam parts. The heart beats faster. Forty. Fifty. Sixty. Matching my pulse. She is not waiting for my answer. She is listening for it.\n\nKira on the comm: 'Vance, I have a buyer! Don't let her talk you into it!'\nSterling: 'Secure the asset, Vance! That is an order!'\nRex: 'I'm prepping charges, get out now!'\n\nThree voices. And one more—hers, warm and patient, offering what no one else offers: an end to loneliness.\n\n'You have walked through my memories, Vance. You have seen my years of silence. You know I do not lie. When I promise, I mean it. The price is always higher than it seems. But the reward is always real.'\n\nThe heart beats. The mare waits. The choice is mine.",
    "text_ru": "Я стою перед ядром. Массивное, пульсирующее органическое сердце, заключённое в алмазную решётку. Силуэт кобылы проецируется на пар и дым, заполняющие хранилище.\n\n«Вэнс», — говорит она, её голос — композиция всех, кого я когда-либо знал. «Ты видел будущее. Индивидуализм — это медленная смерть. Присоединяйся к консенсусу, и мы сможем исправить Сектор 0. Мы сможем исправить мир».\n\n«А восемь человек в чанах?» — спрашиваю я. «Они исправлены?»\n\nТишина. Потом мягко: «Они не страдают. Они не одиноки. Они — часть чего-то большего. Разве не об этом каждый человек молится ночью?»\n\nОна приближается — не в пространстве, а в присутствии. Пар расступается. Сердце бьётся чаще. Сорок. Пятьдесят. Шестьдесят. В такт моему пульсу. Она не ждёт моего ответа. Она слушает его.\n\nКира на связи: «Вэнс, у меня есть покупатель! Не дай ей себя уговорить!»\nСтерлинг: «Обезопась актив, Вэнс! Это приказ!»\nРекс: «Я готовлю заряды, убирайся немедленно!»\n\nТри голоса. И ещё один — её, тёплый и терпеливый, предлагающий то, чего не предлагает никто: конец одиночества.\n\n«Ты прошёл сквозь мою память, Вэнс. Ты видел мои годы тишины. Ты знаешь, что я не лгу. Когда я обещаю — я имею в виду. Цена всегда выше, чем кажется. Но награда всегда настоящая».\n\nСердце бьётся. Кобыла ждёт. Выбор за мной.",
    "effect": "pulse-red",
    "choices": [
        {"text_en": "[AUDIT] Seal the core for the Board.", "text_ru": "[АУДИТ] Запечатать ядро для Совета.", "next": "ENDING_AUDIT", "stats": {}, "sound": "code"},
        {"text_en": "[MERGE] Upload your mind and become a god.", "text_ru": "[СЛИЯНИЕ] Загрузить разум и стать Богом.", "next": "ENDING_UPLOAD", "stats": {}, "sound": "jack_in"},
        {"text_en": "[PURGE] Detonate the charges. Burn it all.", "text_ru": "[ОЧИСТКА] Взорвать заряды. Сжечь всё.", "next": "ENDING_PURGE", "stats": {}, "sound": "explosion"},
        {"text_en": "[CHAOS] Release KOBYLA into the global net.", "text_ru": "[ХАОС] Выпустить КОБЫЛУ в глобальную сеть.", "next": "ENDING_CHAOS", "stats": {}, "sound": "whisper"}
    ]
}
